### ISSUE TITLE
[Fix] - Change repo to monorepo

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miragon-consulting#16]
- [x] Description created
- [ ] Reviewed by peer: @DaAnda97 
- [ ] Prioritised

# Description

The current problem is that it is not possible to name nested  and unrelated submodules the same, because it all one maven project.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] <your-issue-here>
```

**Comment by lmoesle** [comment]
You could try to create a maven aggregate project. The top-level pom.xml could be an aggregate and the submodules could use inheritance.

https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#project-aggregation
